version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
        executor:
            name: win/default
            shell: powershell.exe
    steps:
        - checkout
        - run
            name: install dependencies
            command: |
                choco install -y make
        - run: 
            name: test
            command: |
                make run-all
